---
# Source: argo-application/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-project-workflows-gitops
  namespace: argocd
spec:
  project: test-project
  source:
    repoURL: https://github.com/unbounded-tech/workflows-gitops.git
    targetRevision: v1.3.0
    path: .
    helm:
      values: |
        env:
          test: true
          type: release
          method: promotion
          event: v-tag
  destination:
    server: https://kubernetes.default.svc
    namespace: test-project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
